-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Comunidad"
(
    id_comunidad integer NOT NULL DEFAULT nextval('"Comunidad_id_comunidad_seq"'::regclass),
    id_usuario integer NOT NULL DEFAULT nextval('"Comunidad_id_usuario_seq"'::regclass),
    "fecha_de_publicacion" date,
    "titulo " character varying COLLATE pg_catalog."default",
    "contenido " character varying COLLATE pg_catalog."default",
    "like" integer NOT NULL DEFAULT nextval('"Comunidad_like_seq"'::regclass),
    comentarios character varying COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public."Home_Studio"
(
    "id_configuracion" integer NOT NULL DEFAULT nextval('"Home Studio_id_configuracion_seq"'::regclass),
    nombre character varying COLLATE pg_catalog."default",
    "descripcion " character varying COLLATE pg_catalog."default",
    "Alto_Ancho" bigint,
    material character varying COLLATE pg_catalog."default",
    fecha_creacion date,
    usuario_id integer NOT NULL DEFAULT nextval('"Home Studio_usuario_id_seq"'::regclass),
    costo_estimado bigint,
    equipos_sugeridos "char",
    imagen_referencia "char",
    CONSTRAINT id_home_studio PRIMARY KEY ("id_configuracion")
);

CREATE TABLE IF NOT EXISTS public."Productos "
(
    equipo_id integer NOT NULL DEFAULT nextval('"Productos _equipo_id_seq"'::regclass),
    nombre character varying COLLATE pg_catalog."default",
    precio bigint NOT NULL DEFAULT nextval('"Productos _precio_seq"'::regclass),
    marca character varying COLLATE pg_catalog."default",
    categoria character varying COLLATE pg_catalog."default",
    CONSTRAINT id_productos PRIMARY KEY (equipo_id)
);

CREATE TABLE IF NOT EXISTS public."Temas_SC"
(
    id integer NOT NULL DEFAULT nextval('"Temas_SC_id_seq"'::regclass),
    "Titulo del tema" character varying COLLATE pg_catalog."default",
    "descripcion" character varying COLLATE pg_catalog."default",
    "Categoria" character varying COLLATE pg_catalog."default",
    CONSTRAINT id_temas PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Usuarios"
(
    "id " integer NOT NULL DEFAULT nextval('"Usuarios_codigo _seq"'::regclass),
    "Nombres" character varying COLLATE pg_catalog."default",
    "Apellidos " character varying COLLATE pg_catalog."default",
    "Email" character varying COLLATE pg_catalog."default",
    CONSTRAINT codigo_usuario PRIMARY KEY ("id ")
);

CREATE TABLE IF NOT EXISTS public."Videos "
(
    "id " integer NOT NULL DEFAULT nextval('"Videos _ID_seq"'::regclass),
    titulo character varying COLLATE pg_catalog."default",
    "descripcion" character varying COLLATE pg_catalog."default",
    url character varying COLLATE pg_catalog."default",
    "fecha de carga" date,
    CONSTRAINT pk_codigo_libro PRIMARY KEY ("id ")
);
END;