CREATE TABLE `bmxdb`.`Bike` (
    `Id` INT NOT NULL AUTO_INCREMENT,
    `Name` VARCHAR(45) NULL,
    `Brand` VARCHAR(45) NULL,
    `Model` VARCHAR(45) NULL,
    `Color` VARCHAR(45) NULL,
    `Frame` VARCHAR(45) NULL,
    `Fork` VARCHAR(45) NULL,
    `Bars` VARCHAR(45) NULL,
    `Stem` VARCHAR(45) NULL,
    `Grips` VARCHAR(45) NULL,
    `Seat` VARCHAR(45) NULL,
    `SeatPost` VARCHAR(45) NULL,
    `Cranks` VARCHAR(45) NULL,
    `Pedals` VARCHAR(45) NULL,
    `Sprocket` VARCHAR(45) NULL,
    `FrontWheel` VARCHAR(45) NULL,
    `RearWheel` VARCHAR(45) NULL,
    `FrontTire` VARCHAR(45) NULL,
    `RearTire` VARCHAR(45) NULL,
    `FrontHub` VARCHAR(45) NULL,
    `RearHub` VARCHAR(45) NULL,
    `Chain` VARCHAR(45) NULL,
    `Pegs` VARCHAR(45) NULL,
    PRIMARY KEY (`Id`)
);