import { Inter } from 'next/font/google'
import './globals.css'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        
      </head>
      <body className={inter.className}>
        <nav className="flex items-center justify-between p-4 bg-gray-800 text-white">
          <div className="flex items-center">
            <Image src="/favicon.ico" alt="logo" width={32} height={32} /> 
            <span className="text-xl font-semibold"> PizzaPalace</span> 
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
