INSERT INTO `usersdb`.`users` VALUES
(1, 'Andres.Salazar@email.com','Andres Salazar','Password','ASalazar'), 
(2, 'Jonathan.Asprilla@email.com','Jonathan Asprilla','Password','JAsprilla'), 
(3, 'Julian.Paredes@email.com','Julian Paredes','Password','JParedes'),
(4, 'William.Aguirre@email.com','William Aguirre','Password','WAguirre'),
(5, 'Nicolás.Alvarez@email.com',' Nicolás Alvarez','Password',' Alvarez'),
(6, 'Maria.Carrero@email.com','Maria Carrero','Password','MCarrero'),
(7, 'Nicolas.Ortiz@email.com','Nicolas Ortiz','Password','NOrtiz'),
(8, 'Victor.Ospina@email.com','Victor Ospina','Password','VOspina'),
(9, 'Cristian.Osorio@email.com','Cristian Osorio','Password','COsorio'),
(10, 'Jeison.Garces@email.com','Jeison Garces','Password','JGarces'),
(11, 'Veronica.Tofino@email.com','Veronica Tofino','Password','VTofino'),
(12, 'Laura.Arango@email.com','Laura Arango','Password','LArango'),
(13, 'Juan.Hernandez@email.com','Juan Hernandez','Password','JHernandez'),
(14, 'Ivan.Valderrama@email.com','Ivan Valderrama','Password','IValderrama'),
(15, 'Diego.Galarza@email.com','Diego Galarza','Password','DGalarza'),
(16, 'Tania.Obando@email.com','Tania Obando','Password','TObando'),
(17, 'Jose.Melgarejo@email.com','Jose Melgarejo','Password','JMelgarejo'),
(18, 'Jhoan.Lozano@email.com','Jhoan Lozano','Password','JLozano'),
(19, 'Luis.Oviedo@email.com','Luis Oviedo','Password','LOviedo'),
(20, 'David.Hernandez@email.com','David Hernandez','Password','DHernandez');