"""Pizza, ingredient, order, user models, initial migration 2

Revision ID: 34ba1179d17a
Revises: d9319fb8601a
Create Date: 2023-11-21 14:13:50.776318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34ba1179d17a'
down_revision: Union[str, None] = 'd9319fb8601a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
