"""Pizza, ingredient, order, user models, initial migration con imagenes f 

Revision ID: 4545ce63fe24
Revises: 65a6e4579c2b
Create Date: 2023-11-21 17:15:36.956940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4545ce63fe24'
down_revision: Union[str, None] = '65a6e4579c2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
