"""Pizza, ingredient, order, user models, initial migration con imagenes

Revision ID: 4ac5f348e720
Revises: 34ba1179d17a
Create Date: 2023-11-21 15:44:53.802918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ac5f348e720'
down_revision: Union[str, None] = '34ba1179d17a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
