"""Pizza, ingredient, order, user models, initial migration con imagenes 3 

Revision ID: 65a6e4579c2b
Revises: febad49f4cca
Create Date: 2023-11-21 16:27:25.626560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65a6e4579c2b'
down_revision: Union[str, None] = 'febad49f4cca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
