"""Pizza, ingredient, order, user models, initial migration con imagenes 2

Revision ID: 95c0bcafa4ab
Revises: 4ac5f348e720
Create Date: 2023-11-21 16:03:33.546535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95c0bcafa4ab'
down_revision: Union[str, None] = '4ac5f348e720'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
