"""Pizza, ingredient, order, user models, initial migration con imagenes 3 

Revision ID: febad49f4cca
Revises: 95c0bcafa4ab
Create Date: 2023-11-21 16:10:37.115731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'febad49f4cca'
down_revision: Union[str, None] = '95c0bcafa4ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('image', sa.String(length=300), nullable=True))
    op.add_column('pizzas', sa.Column('images', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pizzas', 'images')
    op.drop_column('ingredients', 'image')
    # ### end Alembic commands ###
