//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapiprueba.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class people
    {
        public int Id { get; set; }
        public string name { get; set; }
        public Nullable<int> age { get; set; }
    }
}
