CREATE TABLE `UsersDB`.`Users` (
    `Id` INT NOT NULL AUTO_INCREMENT,
    `Email` VARCHAR(225) NOT NULL,
    `Name` VARCHAR(50) NOT NULL,
    `Password` VARCHAR(50) NOT NULL,
    `Username` VARCHAR(50) NOT NULL,
    PRIMARY KEY (`Id`));