INSERT INTO `bmxdb`.`User` (
        `Username`,
        `Email`,
        `Password`
    )
VALUES (
        'Hackerman',
        'Hackerman@gmail.com',
        'Hackerman12345@'
    ),
    (
        'User2',
        'Email2@gmail.com',
        'Password2'
    ),
    (
        'User3',
        'Email3@gmail.com',
        'Password3'
    ),
    (
        'User4',
        'Email4@gmail.com',
        'Password4'
    ),
    (
        'User5',
        'Email5@gmail.com',
        'Password5'
    );