DELETE FROM `schooldb`.`SubjectsAndStudents` WHERE SubjectId >= 0;
DELETE FROM `schooldb`.`Subjects` WHERE Id >= 0;
ALTER TABLE `schooldb`.`Subjects` AUTO_INCREMENT = 1;
DELETE FROM `schooldb`.`Students` WHERE Id >= 0;
ALTER TABLE `schooldb`.`Students` AUTO_INCREMENT = 1;

DELETE FROM `schooldb`.`Subjects` WHERE Id >= 0;
ALTER TABLE `schooldb`.`Subjects` AUTO_INCREMENT = 1;
INSERT INTO `schooldb`.`Subjects` (`Name`, `Room`, `Professor`) VALUES('Calculo', '101A', 'Hernando Guerrero');
INSERT INTO `schooldb`.`Subjects` (`Name`, `Room`, `Professor`) VALUES('Fisica', '102A', 'Carlos Garzon');
INSERT INTO `schooldb`.`Subjects` (`Name`, `Room`, `Professor`) VALUES('Etica', '201B', 'Angela Velez');
INSERT INTO `schooldb`.`Subjects` (`Name`, `Room`, `Professor`) VALUES('Logica', '103A', 'Eduardo Ruiz');
INSERT INTO `schooldb`.`Subjects` (`Name`, `Room`, `Professor`) VALUES('Ingles Tecnico', '301B', 'Amparo Sinisterra');

DELETE FROM `schooldb`.`Students` WHERE Id >= 0;
ALTER TABLE `schooldb`.`Students` AUTO_INCREMENT = 1;
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Sofia','Diaz','2002-05-08','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Carlos','Martinez','2003-09-21','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Camila','Rodriguez','2000-11-02','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Juan','Torres','2001-01-15','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Valentina','Hernandez','2002-06-04','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Samuel','Ortiz','2004-08-12','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Luisa','Gonzalez','2003-10-27','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Jorge','Ramirez','2002-12-07','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Lucia','Flores','2000-04-29','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Alejandro','Garcia','2001-07-19','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Maria','Martinez','2004-03-18','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Pablo','Gomez','2002-05-14','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Isabella','Torres','2003-11-10','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Esteban','Hernandez','2001-01-25','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Ana','Gonzalez','2000-09-03','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Diego','Ramirez','2004-02-05','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Valeria','Vargas','2002-08-07','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Guillermo','Torres','2003-06-22','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Lucia','Perez','2001-12-20','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Sofia','Rivera','2000-10-15','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Eduardo','Hernandez','2002-02-09','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Natalia','Rodriguez','2003-07-30','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Sergio','Torres','2000-09-16','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Antonia','Gomez','2001-11-25','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Luis','Martinez','2002-03-06','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Gabriela','Hernandez','2004-05-23','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Felipe','Ramirez','2000-08-02','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Mariana','Gonzalez','2001-01-03','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Mateo','Torres','2002-06-25','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Paola','Diaz','2003-12-13','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Valentina','Gonzalez','2000-09-28','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('David','Ortiz','2002-02-11','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Ricardo','Torres','2004-06-07','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Catalina','Flores','2001-12-31','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Santiago','Ramirez','2002-04-21','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Alejandra','Gomez','2003-11-28','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Emmanuel','Torres','2000-07-02','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Lucia','Martinez','2001-02-23','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Juan','Perez','2003-11-01','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Valentina','Torres','2002-05-16','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Santiago','Fernandez','2001-08-12','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('David','Lopez','2002-06-04','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Mariana','Torres','2003-09-21','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Valentina','Fernandez','2000-04-29','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Jorge','Martinez','2002-01-15','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Lucia','Rodriguez','2003-11-02','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Esteban','Torres','2001-03-18','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Ana','Lopez','2002-07-19','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Felipe','Ruiz','2000-10-27','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Catalina','Gomez','2004-05-08','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Luisa','Hernandez','2001-08-07','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Guillermo','Perez','2002-06-22','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Lucia','Diaz','2003-11-10','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Alejandro','Torres','2000-02-05','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Maria','Ramirez','2003-06-25','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Samuel','Hernandez','2001-12-07','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Valeria','Garcia','2004-09-03','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Pablo','Ortiz','2002-05-14','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Sofia','Torres','2000-01-25','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Eduardo','Ramirez','2003-02-09','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Diego','Martinez','2002-08-02','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Gabriela','Gomez','2000-10-15','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Luis','Torres','2003-03-06','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Natalia','Perez','2001-07-30','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Sergio','Diaz','2002-09-16','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Antonia','Hernandez','2003-11-25','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Mateo','Ramirez','2001-02-11','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Lucia','Gonzalez','2000-08-02','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Valentina','Perez','2003-12-13','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Felipe','Hernandez','2002-04-07','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Mariana','Ramirez','2000-09-28','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('David','Torres','2001-01-03','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Ricardo','Lopez','2003-10-20','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Catalina','Torres','2001-04-21','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Santiago','Torres','2002-12-31','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Alejandra','Gonzalez','2000-06-25','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Emmanuel','Flores','2003-11-01','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Lucia','Torres','2002-05-16','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Camila','Hernandez','2003-02-04','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('José','Ramirez','2001-08-08','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Ana','Torres','2002-01-23','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Samuel','Gonzalez','2000-05-10','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Natalia','Castro','2003-11-14','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Adrián','Torres','2001-06-07','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Laura','Perez','2002-09-30','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Juan','Romero','2000-04-06','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Isabella','Diaz','2001-12-25','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Francisco','Garcia','2003-07-09','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Luciana','Vega','2002-03-16','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Miguel','Torres','2001-11-08','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Andrea','Sánchez','2004-02-19','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Eduardo','Fernandez','2000-06-14','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Julián','Vargas','2002-12-24','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Sonia','Perez','2001-05-27','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Diego','Romero','2003-08-17','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Valeria','Torres','2002-01-05','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Luisa','Perez','2003-04-21','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Carlos','Castro','2001-07-12','M');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Victoria','Gonzalez','2003-12-01','F');
INSERT INTO `schooldb`.`Students` ( `FirstName`, `LastName`, `DateOfBirth`, `Sex`) VALUES ('Veronica','Sandoval','2000-04-10','F');

DELETE FROM `schooldb`.`SubjectsAndStudents` WHERE SubjectId >= 0;
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (1,1);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (2,2);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (3,3);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (4,4);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (5,5);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (1,6);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (2,7);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (3,8);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (4,9);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (5,10);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (1,11);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (2,12);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (3,13);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (4,14);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (5,15);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (1,16);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (2,17);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (3,18);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (4,19);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (5,20);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (1,21);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (2,22);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (3,23);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (4,24);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (5,25);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (1,26);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (2,27);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (3,28);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (4,29);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (5,30);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (1,31);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (2,32);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (3,33);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (4,34);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (5,35);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (1,36);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (2,37);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (3,38);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (4,39);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (5,40);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (1,41);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (2,42);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (3,43);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (4,44);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (5,45);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (1,46);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (2,47);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (3,48);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (4,49);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (5,50);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (1,51);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (2,52);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (3,53);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (4,54);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (5,55);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (1,56);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (2,57);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (3,58);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (4,59);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (5,60);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (1,61);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (2,62);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (3,63);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (4,64);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (5,65);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (1,66);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (2,67);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (3,68);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (4,69);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (5,70);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (1,71);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (2,72);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (3,73);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (4,74);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (5,75);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (1,76);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (2,77);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (3,78);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (4,79);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (5,80);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (1,81);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (2,82);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (3,83);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (4,84);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (5,85);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (1,86);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (2,87);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (3,88);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (4,89);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (5,90);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (1,91);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (2,92);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (3,93);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (4,94);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (5,95);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (1,96);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (2,97);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (3,98);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (4,99);
INSERT INTO `schooldb`.`SubjectsAndStudents` (`SubjectId`, `StudentId`) VALUES (5,100);

